### ISSUE TITLE
use bytewise range slicing

### ISSUE THREAD

**Issue by deanlandolt** [vweevers/level-scout#1]
This looks awesome! Just to give you a heads up, I cut a v1.0 of `bytewise` yesterday, and started adding support for building type-specific ranges which might be useful. Here are some preliminary tests that should show the basic idea: https://github.com/deanlandolt/bytewise-core/blob/master/test/ranges.js

Still a little more work to do but it might be worth taking a look at for level-scout. If there's something in particular you'd need, just let me know.

**Comment by vweevers** [comment]
Updated to 1.0, thanks! level-scout wouldn't be possible (or well, as easy) without bytewise. Type-specific ranges sound cool, did you have a use in mind? Or what inspired you to start working on this?

**Comment by deanlandolt** [comment]
Supporting the kind of thing you're building here is one of the primary use cases -- other folks are doing some interesting things with queries, so it'd be good to offer some API surface for building queries reliably.

Another use case is to define key paths as [uris](https://github.com/deanlandolt/bytewise-uri) -- turns out you can build a pretty robust type system from this, with type checking reduced to bitwise compare operations.

**Comment by vweevers** [comment]
Ah, the readme of `bytewise-uri` is a great write-up, thanks. I was a little lost in the woods before, with `bytewise(-core)` and `typewise(lite)(-core)`. I'm already solving too many problems in level-scout though (it should be abstracted and split up eventually), so I'll come back to this later.

**Comment by deanlandolt** [comment]
Understandable :)

Just to give you a little context, `typewiselite` was just something dominictarr did to pare back some of the more half-baked ideas I'd originally included in `typewise` (many of which have found a home in `bytewise-uri`). I stripped out most of that stuff from `typewise` and created `typewise-core` to hopefully fill the role of `typewiselite`, but in a way that can be extended to inject more interesting data structures.

The same could be said of `bytewise` itself -- originally I'd thought of it as a general purpose encoding it really only gets used for key paths. So I ripped out things like `object` and `function` serialization and rewrote it (as `bytewise-core`) so that this kind of stuff could be layered on later.

As it stands, `bytewise` is just a proxy to `bytewise-core` -- it doesn't add anything interesting, and the same is true for `typewise` (it just exports `typewise-core`). IIUC all you'd really need for `level-scout` is `bytewise-core` -- arrays, strings, numbers, dates, bool, null -- maybe not even all that. The other feature it adds are the utilities for generating ranges and prefixed queries based on the boundary values of different types. Perhaps not necessary for your use cases, but if you find yourself doing a bunch of bit twiddling as you're constructing complex queries it's probably worth taking a look closer look. I just wanted to point out to you in case it could be helpful.

**Comment by vweevers** [comment]
level-scout might not need bytewise at all, well I mean, as a direct dependency. I'm considering using dominictarr's [ltgt](https://github.com/dominictarr/ltgt) (or something similar) for filtering, because there's no need for a sort order there (property predicates can be evaluated individually), and to let `level-sublevel` handle the bytewise en/decoding for index writing and scanning.

> Perhaps not necessary for your use cases, but if you find yourself doing a bunch of bit twiddling as you're constructing complex queries it's probably worth taking a look closer look.

:+1: `process.futureTick()`. I'll keep it in mind, and I'll know who to /cc.

> I just wanted to point out to you in case it could be helpful.

Any and all help is much appreciated.
